### ISSUE TITLE
Excel file

### ISSUE THREAD

**Issue by Britt202112** [boivinalex/vivino-recommenderpy#1]
Dear Alex,

I am wondering whether you could help me. I am a student and I am working on my master thesis. I am searching for the dataset that you are using in the vivino-recommender. The Python scrape code isn't work at my laptop. Could you maybe share the excel file? 

You would be a HERO! Thank you in advance,

Kind regards,
Britt

**Comment by boivinalex** [comment]
Added some sample data to the repo. Good luck with your masters!
